apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ord.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hlf-ord.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7050
      protocol: TCP
      name: grpc
    {{- if eq .Values.ord.metrics.provider "prometheus" }}
    - port: {{ .Values.service.portMetrics }}
      targetPort: 9443
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "hlf-ord.selectorLabels" . | nindent 4 }}
