stages:
  - docker
  - helm

variables:
  GIT_SUBMODULE_STRATEGY: recursive

docker-helper:
  image:
    name: registry.gitlab.com/xdev-tech/build/docker:2.2
  stage: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build_with_helm_tag $CI_REGISTRY_IMAGE/helper hlf-peer helper

docker-fabcar:
  image:
    name: registry.gitlab.com/xdev-tech/build/docker:2.2
  stage: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build $CI_REGISTRY_IMAGE/fabcar fabcar

docker-ccid:
  image:
    name: registry.gitlab.com/xdev-tech/build/docker:2.2
  stage: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build_with_helm_tag $CI_REGISTRY_IMAGE/ccid hlf-peer ccid

helm-ord:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:2.2
  script:
    - build_std ./hlf-ord NO_PATCH

helm-peer:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:2.2
  script:
    - build_std ./hlf-peer NO_PATCH

helm-chaincode:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:2.2
  script:
    - build_std ./hlf-chaincode NO_PATCH

helm-ord-oci:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:2.2
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build $CI_REGISTRY_IMAGE/helm/hlf-ord ./hlf-ord NO_PATCH

helm-peer-oci:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:2.2
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build $CI_REGISTRY_IMAGE/helm/hlf-peer ./hlf-peer NO_PATCH

helm-chaincode-oci:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:2.2
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build $CI_REGISTRY_IMAGE/helm/hlf-chaincode ./hlf-chaincode NO_PATCH
