stages:
  - docker
  - helm

variables:
  GIT_SUBMODULE_STRATEGY: recursive

docker-ccs-builder:
  image:
    name: registry.gitlab.com/xdev-tech/build/docker:2.0
  stage: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build $CI_REGISTRY_IMAGE/fabric-ccs-builder fabric-ccs-builder

docker-fabcar:
  image:
    name: registry.gitlab.com/xdev-tech/build/docker:2.0
  stage: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build $CI_REGISTRY_IMAGE/fabcar fabcar

helm-ord:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:develop
  script:
    - build_std ./hlf-ord

helm-peer:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:develop
  script:
    - build_std ./hlf-peer

helm-chaincode:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:develop
  script:
    - build_std ./hlf-chaincode
