{{- if .Values.couchdb.enabled }}
{{- $name := printf "%s-couchdb" (include "hlf-peer.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hlf-peer.labels" . | nindent 4 }}
    app.kubernetes.io/component: couchdb
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  COUCHDB_USER: {{ .Values.couchdb.user | b64enc }}
{{- include "hlf-peer.automaticSecret" (list . $name "COUCHDB_PASSWORD" 20 .Values.couchdb.password) }}
{{- end }}
