apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hlf-peer.labels" . | nindent 4 }}
    app.kubernetes.io/component: peer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portRequest }}
      targetPort: 7051
      protocol: TCP
      name: request
    - port: {{ .Values.service.portEvent }}
      targetPort: 7053
      protocol: TCP
      name: event
    {{- if eq .Values.peer.metrics.provider "prometheus" }}
    - port: {{ .Values.service.portMetrics }}
      targetPort: 9443
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "hlf-peer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: peer
