{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hlf-peer.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hlf-peer.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.peer.tls.server.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    {{- else }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.secretName | default (printf "%s-tls" $fullName) }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: request
{{- end }}
